start stop scripts, make release, deploy fixes

diff --git a/bin/vcache-mgr-start b/bin/vcache-mgr-start
--- a/bin/vcache-mgr-start
+++ b/bin/vcache-mgr-start
@@ -30,7 +30,7 @@ if [[ $? != 0 ]]; then
 	exit 1
 fi
 
-DC_VERSION=$(sudo docker-compose version)
+DC_VERSION=$(sudo docker-compose version | head -n 1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
 if [ $? != 0 ]; then
     echo "please install docker-compose and provide sudo access..."
     exit 2
@@ -38,12 +38,23 @@ else
 	echo "running docker-compose (>= 1.29 required): ${DC_VERSION}"
 fi
 
-sudo docker-compose ps --services --filter "status=running" 2>/dev/null | grep "vcache" > /dev/null
+sudo docker-compose ps --services --filter "status=running" 2>/dev/null | grep -w "vcache_mgr" > /dev/null
 
 if [ $? == 0 ]; then
-	echo "vcache containers already running..."
+	echo "vcache manager containers already running..."
 	exit 3
 fi
+
+VCACHE_MGR_VERSION=`git describe 2> /dev/null`
+if [[ $? != 0 ]]; then
+	if [[ -r .version ]]; then
+		VCACHE_MGR_VERSION=`cat .version`
+	else
+	    echo "[$?]no git revision or version.txt file detected, using: 0.0.0"
+	    VCACHE_MGR_VERSION="0.0.0"
+	fi
+fi
+export VCACHE_MGR_VERSION
 
 if [[ -f .env && -r .env ]]; then
 	echo "using existing .env file..."
@@ -54,42 +65,19 @@ else
 	echo "generating .env file..."
 	read -p "enter the vcache hostname[$HOSTNAME]: " hostname
 	hostname=${hostname:-$HOSTNAME}
-    echo "VCACHE_HOSTNAME=${hostname}" > .env
-	echo "VCACHE_MEM_SIZE=12G" >> .env
+    echo "VCACHE_MGR_HOSTNAME=${hostname}" > .env
 fi
 
-VCACHE_VERSION=`git describe 2> /dev/null`
-if [[ $? != 0 ]]; then
-	if [[ -r ./run/vcache-version.txt ]]; then
-		VCACHE_VERSION=`cat ./run/vcache-version.txt`
-	else
-	    echo "[$?]no git revision or version.txt file detected, using: 0.0.0"
-	    VCACHE_VERSION="0.0.0"
-	fi
-fi
-echo -n ${VCACHE_VERSION} > ./run/vcache-version.txt
-
-
-# read the config and eval templates for nginx and varnish
-if [[ ! -e ./conf/vcache.cfg && -e ./conf/vcache.cfg.dist ]]; then
-	cp ./conf/vcache.cfg.dist ./conf/vcache.cfg
-fi
-									  
-./bin/vcache-cfg-update
-
-if [[ $? != 0 ]]; then
-	echo "error updating vache cfg files ($?)"
-	exit 7
+if [[ "$VCACHE_MGR_VERSION" != "0.0.0" ]]; then
+    # update or add the VCACHE_MGR_VERSION to .env
+    perl -i -ne "\$found++ if s/VCACHE_MGR_VERSION=\S+/VCACHE_MGR_VERSION=${VCACHE_MGR_VERSION}/;\
+ \$_ .= \"VCACHE_MGR_VERSION=${VCACHE_MGR_VERSION}\\n\" if eof and not \$found; print;" .env
 fi
 
 echo "cleaning up previous deployment..."
 sudo docker-compose down
 
-rm -f run/*.sock run/*.pid
-# XXX there must be a better way to grant write perms to containers
-chmod ugo+rwx log run etc/varnishstats
-
-echo "starting vcache (${VCACHE_VERSION}) ..."
+echo "starting vcache manager (${VCACHE_MGR_VERSION}) ..."
 
 if [[ $debug ]]; then
 	sudo docker-compose up
@@ -98,10 +86,10 @@ else
 fi
 
 if [[ $? != 0 ]]; then
-	echo "[$?] an error occured starting vcache, exiting..."
+	echo "[$?] an error occured starting vcache manager, exiting..."
 	exit 4
 else
-	echo "vcache started!"
+	echo "vcache manager started!"
 fi
 
 exit 0
